// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDB_MIA.Data;

namespace WebDB_MIA.Migrations
{
    [DbContext(typeof(WebDB_MIAContext))]
    partial class WebDB_MIAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebDB_MIA.Models.Casualtie", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Casualtie");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Criminal", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CasualtiesID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypesCrimesID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CasualtiesID");

                    b.HasIndex("StaffID");

                    b.HasIndex("TypesCrimesID");

                    b.ToTable("Criminal");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Position", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Duties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Rank", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Duties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Staff", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<long?>("PositionID")
                        .HasColumnType("bigint");

                    b.Property<long?>("RankID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PositionID");

                    b.HasIndex("RankID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("WebDB_MIA.Models.TypeCrime", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Judgment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TypeCrime");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Criminal", b =>
                {
                    b.HasOne("WebDB_MIA.Models.Casualtie", "Casualties")
                        .WithMany("Criminal")
                        .HasForeignKey("CasualtiesID");

                    b.HasOne("WebDB_MIA.Models.Staff", "Staff")
                        .WithMany("Criminal")
                        .HasForeignKey("StaffID");

                    b.HasOne("WebDB_MIA.Models.TypeCrime", "TypesCrimes")
                        .WithMany("Criminal")
                        .HasForeignKey("TypesCrimesID");

                    b.Navigation("Casualties");

                    b.Navigation("Staff");

                    b.Navigation("TypesCrimes");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Staff", b =>
                {
                    b.HasOne("WebDB_MIA.Models.Position", "Position")
                        .WithMany("Staff")
                        .HasForeignKey("PositionID");

                    b.HasOne("WebDB_MIA.Models.Rank", "Rank")
                        .WithMany("Staff")
                        .HasForeignKey("RankID");

                    b.Navigation("Position");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Casualtie", b =>
                {
                    b.Navigation("Criminal");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Position", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Rank", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("WebDB_MIA.Models.Staff", b =>
                {
                    b.Navigation("Criminal");
                });

            modelBuilder.Entity("WebDB_MIA.Models.TypeCrime", b =>
                {
                    b.Navigation("Criminal");
                });
#pragma warning restore 612, 618
        }
    }
}
